### ISSUE TITLE
Critical issues

### ISSUE THREAD

**Issue by encukou** [pyvec/arca#20]
* [x] The repo_id method doesn't return unique identifiers, and it's probably possible to register a domain that clashes with a valid one. You can just append a hash to make it unique. 
    Also, use `replace` instead of `"_".join(repo.split("/"))` :)
* [x] `is_dirty` looks at the current directory. This is confusing (non-intuitive if you look at the name/signature alone). Please make it take the directory as argument.
* [x] Please pass the `Task` entrypoint and arguments in a JSON file, and have a static script that loads that and executes it. That should be much easier to reason about than generating Python code programatically. (easier to reason about == easier to debug and secure)

**Comment by mikicz** [comment]
Removed ``Arca.is_dirty`` entirely, replaced the call in naucse with a call to the function ``arca.utils.is_dirty`` which does require the directory as an argument and was in fact called by ``Arca.is_dirty``... (61fc266df762f184de1d68e7cdfb6820b711385a)

**Comment by mikicz** [comment]
Fixed ``Arca.repo_id`` in 3fbf16a304c787eea69c641fb8ae55f7e555b8fa, also replaced sha1 usages in Arca with sha256.

**Comment by mikicz** [comment]
Could you please take a look at #25, the implementation of the third part of this issue?
