### ISSUE TITLE
Set a timeout for execution of tasks

### ISSUE THREAD

**Issue by mikicz** [pyvec/arca#41]

**Comment by hroncok** [comment]
subprocess: stick a timeout into communicate() https://github.com/mikicz/arca/blob/4294e981914bca229d89a12ada86f73f546da6f8/arca/backend/base.py#L161

**Comment by hroncok** [comment]
If [docker](https://docker-py.readthedocs.io/en/stable/containers.html) doesn't provide a good timeout option, you can always use the [timeout](https://linux.die.net/man/1/timeout) command.

**Comment by mikicz** [comment]
Pushed to #40, I set the default timeout to 5 seconds... I still need to update the documentation...
