### ISSUE TITLE
Invalid Pipenv.lock causes Arca exception

### ISSUE THREAD

**Issue by encukou** [pyvec/arca#56]
It looks like [this commit](https://github.com/muzikovam/naucse.python.cz/commit/9de9fe56855b2649d4daf8cc06db4725ed7808d2) broke naucse.

I'm not sure if it's a bug in Arca itself, or naucse's use of Arca.

**Comment by mikicz** [comment]
I think it'a bug in Arca.

This snippet in DockerBackend which handles failure of building docker images should raise arca's `BuildError`, not docker's. Working on a fix.

```
        except docker.errors.BuildError as e:
            for line in e.build_log:
                if isinstance(line, dict) and line.get("errorDetail") and line["errorDetail"].get("code") in {124, 143}:
                    raise BuildTimeoutError(f"Installing of requirements timeouted after "
                                            f"{self.requirements_timeout} seconds.")

            logger.exception(e)
            raise
```
